name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    env:
      LANG: it_IT.utf8
      LIMIT_JEST: yes
      TZ: Europe/Rome

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn run test:prod && npm run build
      - run: bash <(curl -s https://codecov.io/bash) -Z -t d0c9306f-82e3-462d-b99a-21abdb3b7521

